Repository websentry/WebSentry, pull requests merged in 2020-07, with the labels that each got.

#41 Add transaction support part2.
  controllers/sentry.go
  go.mod
  models/notification.go
  models/sentry.go
Labels: enhancement

#42 add transaction support in user related functions
  controllers/user.go
  models/user.go
Labels: enhancement

#43 Refactor init process && Support custom config path
  config/config.go
  controllers/common.go
  controllers/slave.go
  go.mod
  main.go
  middlewares/common.go
  middlewares/slaveAuth.go
  server/server.go
  utils/common.go
  utils/email.go
  utils/image.go
  utils/token.go
Labels: enhancement

#44 Add functional testing framework
  functional_test/.gitignore
  functional_test/__init__.py
  functional_test/helper.py
  functional_test/main.py
  functional_test/requirements.txt
  functional_test/tests.py
Labels: enhancement

#45 Reimplement github action for ci/cd
  .github/workflows/build.yml
  .github/workflows/main.yml
  Dockerfile.ci
Labels: enhancement

#47 Rename "slave" to "worker"
  README.cn.md
  README.md
  config.exmaple.json
  config/config.go
  controllers/common.go
  controllers/worker.go
  docs/assets/architecture.png
  functional_test/main.py
  middlewares/common.go
  middlewares/limiter.go
  middlewares/workerAuth.go
  server/router.go
Labels: enhancement

#48 Fix docker image build by github action.
  .github/workflows/main.yml
  Dockerfile
Labels: bug

#49 FIx a bug that cause UpdateSentryAfterCheck fail.
  models/sentry.go
Labels: bug

#50 Fix sentryinfo api and add more logging
  controllers/sentry.go
  controllers/worker.go
  server/router.go
Labels: bug, enhancement

#53 Refactor Verification Code && Add Limiter && Remove Remaining Count
  controllers/user.go
  models/migration.go
  models/model.go
  models/user.go
Labels: enhancement

#55 Support pause sentry && update sentry settings && bug fix.
  controllers/response.go
  controllers/sentry.go
  go.mod
  models/common.go
  models/enum.go
  models/migration.go
  models/model.go
  models/notification.go
  models/sentry.go
  models/user.go
  server/router.go
Labels: bug, enhancement
